# Generated by Django 4.0.1 on 2022-01-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userstatistics'),
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statistics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userstatistics', verbose_name='user statistics'),
            preserve_default=False,
        ),
    ]
