# Generated by Django 4.0.1 on 2022-01-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='statistics',
        ),
    ]
