# Generated by Django 4.0.1 on 2022-01-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
            ],
        ),
    ]
