# Generated by Django 4.0.1 on 2022-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quote_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_started', models.IntegerField(default=0)),
                ('tests_completed', models.IntegerField(default=0)),
                ('time_typing', models.IntegerField(default=0)),
            ],
        ),
    ]
