# Generated by Django 4.0.1 on 2022-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='cpm',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time',
            field=models.FloatField(),
        ),
    ]
